# Generated by Django 4.2.13 on 2024-07-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_like_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
