# Generated by Django 4.2.13 on 2024-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_options_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
